Show the errnum on ssh error

diff --git a/cgmonitor b/cgmonitor
--- a/cgmonitor
+++ b/cgmonitor
@@ -56,7 +56,7 @@ RES=$(sshpass -p admin ssh -oStrictHostKeyChecking=no -l root $_IP /sbin/reboot 
 if [ "$?" -eq "0" ]; then
   echo Rebooting
 else
-  echo Error
+  echo "Error: $?"
 fi
 }
 
